### ISSUE TITLE
Request.Network - integration to pay invoices with NEAR Wallet

### ISSUE THREAD

**Issue by Kisgus** [near/bounties#46]
# Description

Enable to approve and pay  request.network invoices denominated in NEAR via the [NEAR wallet](https://wallet.near.org/).
 
## Context

Request is an invoicing and payment protocol originally built on Ethereum. All invoices and their lifecycle statuses (creation, approval, payment, cancellation, etc.) are recorded on the blockchain. The crypto invoicing solution; [Request Invoicing](https://invoicing.request.network/) is a transaction engine for crypto-first organizations such as Foundations, DeF projects and DAOs, which enable anyone from contractors to institutions to issue invoices and get paid in crypto. 

## Implementation overview

We want to add a new payment network to request and enable payments with NEAR tokens. We need 3 components:

- A paymentProxy smart contract, deployed on NEAR
- A way to index interesting events sent by the proxy
- A way to get details of an event emitted by the proxy

**NB: This project focuses on payments, requests hashes are still stored on Ethereum.**

### PaymentProxy smart contract

The code should be strictly equivalent to the [Ether proxy payment contract](https://etherscan.io/address/0x37a8f5f64f2a84f2377481537f04d2a59c9f59b6%23code) on Ethereum, at the address 0x37A8f5F64f2a84f2377481537F04D2A59C9f59B6.
The code is also available on our GitHub: https://github.com/RequestNetwork/requestNetwork/blob/master/packages/smart-contracts/src/contracts/EthereumProxy.sol

A payment of amount NEAR for a recipient and payment reference should through this event:

```
event TransferWithReference(
address to,
uint256 amount,
bytes indexed paymentReference);
```

### Index events sent by the proxy
Some parts of our infrastructure need to index request payments per block. We need to index all transactions that have sent events from this payment contract, per block or block range, with a web RPC provider.

We also need to index events by paymentReference, as this is the way we can retrieve the payment status of one specific invoice.

### Get details of the events
For each payment we retrieve the parameters to, amount and paymentReference.

# Acceptance Criteria

To make a flawless NEAR request.network integration we expect the following components to be delivered:  

- [x] Contract code in Rust
- [x] Deployed contract on Near
- [x] Snippet of Typescript code that can retrieve payments in the last block, if any
- [x] Snippet of Typescript code that can retrieve payments for one paymentReference
- [x] Any advice or feedback is welcome :)

# Bounty

10k USD worth of NEAR

# Contact
You can ask for technical support in the [NEAR](https://discord.com/invite/UY9Xf2k) or [Request](https://discord.com/invite/q7cRv4hT) Discord.

**Comment by hackphobic** [comment]
I can finish finish this soon. 
In what format do you need the queried events?

**Comment by yomarion** [comment]
> I can finish finish this soon.
> In what format do you need the queried events?

@hackphobic We need the transactions and their logs to infer the concerned requestIds

**Comment by Kisgus** [comment]
Great @hackphobic do you have any estimate on when you will be able to start / finalize the implementation?

**Comment by hackphobic** [comment]
@Kisgus it should be ready within two days, I only have the testing part left but I also wanna improve some parts too.

**Comment by Kisgus** [comment]
Great news @hackphobic, thanks, we look forward to start testing it!

**Comment by hackphobic** [comment]
@Kisgus sorry for the delay but this PR needs to be included before it's possible to query and blocks and txs for the contract events
https://github.com/near/near-api-js/pull/534

**Comment by Kisgus** [comment]
Hey @hackphobic thanks for letting me now, is the merge 12 hours ago sufficient?

**Comment by Kisgus** [comment]
Whats your eta now @hackphobic ? Any blockers?

**Comment by hackphobic** [comment]
@Kisgus yes actually I ran into a couple more issues in Near-api-js and they're fixed now. I believe I have all the working parts, it's a matter of putting them together in the Request package architecture.  

I'm currently trying to add the NEAR fungible token standard. 
also, blocks are garbage collected by nodes after 5 epochs. which means we can't query blocks older than about 2.5 days and I don't know of a public indexer yet. I will look into this later.

**Comment by Kisgus** [comment]
I see thanks for elaborating. Yes we do have an indexer @hackphobic, please send me your Telegram handle, publicly here or to gustav@near.org and I will provide you a start guide for that

**Comment by DenysOf** [comment]
Is this still open? Our company is interested in the task. Thanks.

**Comment by Kisgus** [comment]
I've assinged you now @DenysOf as this has still not been resolved. Please let me know if you need any additional input.

**Comment by cameron-NEAR** [comment]
Hey @DenysOf, would you mind providing a quick update on the progress of this bounty? 

@hackphobic, are you still interested in completing this?

**Comment by DenysOf** [comment]
> Hey @DenysOf, would you mind providing a quick update on the progress of this bounty?
> 
> @hackphobic, are you still interested in completing this?

Hi @cameron-NEAR, this is completed and handed over to Request for the integration. It is also pending smart-contract review/audit. We are waiting for Request to confirm and accept.

**Comment by Kisgus** [comment]
Can confirm this is pending request.network team integration as of now @cameron-NEAR, we keep providing them with inputs to go into production. @hackphobic stopped responding to us a long time ago.

**Comment by AngelBlock** [comment]
@cameron-NEAR this bounty is completed.

**Comment by AngelBlock** [comment]
The source code is published at https://github.com/near-request/request-network
RequestNetwork is finalising the integration and mainnet contract is deployed.

Pending

- [ ] Contract review by internal resources
- [ ] Contract audit by third party audit company (if required)

**Comment by Kisgus** [comment]
Awesome thanks a lot for the work @DenysOf & @yomarion on this. The bounty is considered completed now as audit was not part of the initial specification. Looking forward to the launch soon!
